const cityLabs = {
    "BATANGAS": ["MEDIC8 MEDICAL & DIAG CENTER INC.", "COMMON CARE MED CLINIC", "RightPat DIAG LAB"],
    "BULACAN": ["RABV CLINICAL LAB", "RABV DRUGTESTING LAB","MGP/LABWORKS","MIRACULOUS BALAGTAS","EXCELGENICS","JLS PANDI",
        "JLSBATIAWJE","ARCHANGELS","BULACAN DIAGNOSTIC","METRO SAN JOSE","GALVEZ HOSPITAL","MJ SCREENING DRUG TEST","MT CARMEL","SAGRADA FAMILIA HOSP",
        "SI DOCTORS SPECIALTY CLINIC ","ST. SEBASTIAN DIAGNOSTIC LAB ","FASTHEALTH","SAN LUIS CASTILLO DIAG LAB(MEYCA)","HEALTH TRUE VALUE",
        "RAPOLI LAB CLINIC","BAUTISTA-BASALIO CLINIC","CALIBRE","VM BERNABE MED DIAG CLINIC","CFD HEALTH CARE","DR. ROQUERO HOSPITAL","JCMC","MC GENESIS LAB","RRT",],
    "CALOOCAN": ["CLINICA SAN JUDIEL","ST. THADDUES","NODADO","DOMINICO LAB","DOMINICO LAB DTL","VILLAFRIA HEALTHCARE","HEALTHYLINK","EUXIR WATER LAB","Q.IMAGO","A&K VALDEZ MEDICAL CLINIC",],
    "PAMPANGA": ["ANABELLE LAB", "JHAYEN MEDICALHEMOLINE (AVIE ANGELES) ", "ED LIM MATERNITY CLINIC","ACESO HEALTH CARE","PDDL","EM-EL LAB",],
    "TARLAC": ["MANUFEL DIAGNOSTIC LAB (MAGNATECH)", "STO NINO HOSPITAL ",],
    "QUEZON PROVINCE": ["OMRI LABORATORY", "JHAYEN MEDICALHEMOLINE (AVIE ANGELES) ", "ED LIM MATERNITY CLINIC","ACESO HEALTH CARE","PDDL","EM-EL LAB",],
    "MANILA": ["ANONAS LAB",],
    "QUEZON PROVINCE": ["OMRI LABORATORY", "JHAYEN MEDICALHEMOLINE (AVIE ANGELES) ", "ED LIM MATERNITY CLINIC","ACESO HEALTH CARE","PDDL","EM-EL LAB",],
    "QUEZON CITY": ["BMCI", "MAGNATECH", "3 KINGS","HOPE GEN","SUREHEALTH","GABON LAB","WESTVIEW","INTEGRITY DIAGNOTICS LAB","SAN LORENZO HOSPITAL LAGRO","SAN LORENZO HOSPITAL DEPARO","ST. BLAIZE",],
    
  };
  
  export default cityLabs;
  